### ISSUE TITLE
Improve implementation of texture workflow 

### ISSUE THREAD

**Issue by yxqd** [ornlneutronimaging/braggedgemodeling#37]
The workflow converts data measured by VULCAN to Bragg edge spectrum. 

This is a followup of #36.

* [ ] #32 The vdrive to mtex conversion seems to be limited to a few hkls. 
* [ ] #33 Should extract hkl values automatically from rpf files
* [ ] #34 Make texture2R more pythonic
* [ ] #35 Split workflow test script to 4 steps
